In [5]:
%pip install pandas
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
doctor=pd.read_csv("/workspaces/CareFlow-Clinical-Pathway-Process-Mining/doctors.csv")

In [7]:
doctor.head()

,doctor_id,doctor_name,specialization,department,doctor_type,experience_years,consultation_fee,doctor_shift,max_patients_per_day
0,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0
1,DOC511,Dr. Venkatesh Kulkarni,ENT Specialist,ENT,OPD Only,5,800,Morning,50
2,DOC512,Dr. Mohammed Arora,Neurologist,Neurology,Both,6,1500,Morning,45
3,DOC513,Dr. Shweta Mittal,Pulmonologist,Pulmonology,IPD Only,33,1000,Morning,0
4,DOC514,Dr. Parminder Reddy,Orthopedic Surgeon,Orthopedics,Both,17,1000,Evening,42

In [9]:
patient=pd.read_csv("/workspaces/CareFlow-Clinical-Pathway-Process-Mining/patients.csv")

In [10]:
patient.head()

,patient_id,patient_category,patient_type,visit_type,gender,age,blood_group,area,disease,severity_level,...,admission_date,discharge_date,doctor_id,treatment_cost,payment_method,insurance,patient_status,opd_waiting_time_min,room_allocation_time_min,patient_rating
0,PAT320001,Appointment,OPD,New Patient,Male,32,A+,Sector 15,Fever,Moderate,...,2026-06-22,2026-06-22,DOC550,2003,Debit Card,No,Recovered,25,0,5.0
1,PAT320002,Walk-in,OPD,New Patient,Female,12,AB-,Sector 15,Malaria,Moderate,...,2026-06-25,2026-06-25,DOC541,4318,Credit Card,No,Recovered,66,0,2.0
2,PAT320003,Appointment,OPD,New Patient,Male,1,O+,Sector 21,Child Asthma,Moderate,...,2026-06-08,2026-06-08,DOC538,2775,Debit Card,No,Recovered,12,0,4.0
3,PAT320004,Appointment,OPD,New Patient,Male,82,A+,DLF Phase 2,Stroke,Severe,...,2026-06-22,2026-06-22,DOC512,3774,UPI,No,Recovered,20,0,4.0
4,PAT320005,Emergency,IPD,New Patient,Male,19,B+,Sector 21,Road Accident,Severe,...,2026-06-15,NaN,DOC521,59018,Credit Card,No,Recovered,0,21,5.0

In [12]:
hospital=pd.merge(doctor, patient, on="doctor_id")

In [14]:
hospital.head()

,doctor_id,doctor_name,specialization,department,doctor_type,experience_years,consultation_fee,doctor_shift,max_patients_per_day,patient_id,...,referral_source,admission_date,discharge_date,treatment_cost,payment_method,insurance,patient_status,opd_waiting_time_min,room_allocation_time_min,patient_rating
0,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320065,...,Self,2026-06-16,2026-06-16,1037,UPI,No,Recovered,56,0,4.0
1,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320226,...,Self,2026-06-16,2026-06-16,4349,UPI,No,Recovered,26,0,4.0
2,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320286,...,Doctor Referral,2026-06-10,2026-06-17,65745,Credit Card,No,Recovered,0,58,3.0
3,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320346,...,Self,2026-06-08,2026-06-08,2374,UPI,Yes,Recovered,74,0,4.0
4,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320349,...,Doctor Referral,2026-06-17,2026-06-17,7509,UPI,No,Recovered,6,0,3.0